# Database configuration
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

# JPA configuration
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect

      # Configure Hibernate to show SQL
#    show-sql: true
#    properties:
#       hibernate:
#       format_sql: true

  # Create script sql "create.sql" files in src/main/resources

    hibernate:
       ddl-auto: create
    properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          hbm2ddl:
            delimiter: ";"
          jakarta:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: create
                create-target: create.sql
