on:
  push:    
    tags:
      - 'v*' 

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1       
        with:
          node-version: 16.x                    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}          
          draft: false
          prerelease: false