on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build project and create zip
        run: |
          echo "Building project..."
           zip -q -r dslist.zip .  # Comando para gerar o arquivo ZIP com os arquivos do projeto
          ls -l *.zip         

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dslist.zip
          prerelease: false
          body_path: CHANGELOG.md