on:
  push:
    tags:
      - 'v*' # Push events to matching v*, e.g., v1.0, v20.15.10

name: Create Release with Asset

jobs:
  release:
    name: Build and Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Release Asset Directory
        run: mkdir -p dslist

      - name: Build Release Asset
        run: |
          # Verify directory existence and compress files
          if [ -d "dslist" ]; then
            zip -q -r dslist.zip dslist
            echo "Asset created: dslist.zip"
          else
            echo "'dslist' directory not found. Skipping asset creation."
            exit 0
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: changelog.md
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: success() && steps.create_release.outputs.upload_url
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dslist.zip
          asset_name: dslist.zip
          asset_content_type: application/zip
