on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release with Asset (Improved)

jobs:
  build:
    name: Upload Release Asset (with checks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create 'dslist' directory
        run: mkdir -p dslist

      - name: Verify directory existence (optional)
        run: |
          if [ ! -d "dslist" ]; then
            echo "Skipping asset upload: 'dslist' directory not found."
            exit 0
          fi
        # This step is optional and can be removed if preferred

      - name: Build Release Asset
        run: |
          # Compress only if the directory exists
          if [ -d "dslist" ]; then
            zip -q -r dslist.zip ./*
          fi
          # List any zip files created (optional)
          ls -l *.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: changelog.md
          draft: false
          prerelease: false

      - name: Upload Release Asset (if zip exists)
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dslist.zip  # Use relative path
          asset_name: dslist.zip
          asset_content_type: application/zip

        # Only upload if the build step ran successfully
        if: success() && steps.build.outputs.run == '0'
