on:
  push:    
    tags:
      - 'v*' 

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Primeira Release

           # - Primeira Mudança:
            #  Adicionado OpenShell.efi.

            #- Segunda Mudança:
            #  Recomendado para depuração, a partir do menu do OpenCore.
          draft: false
          prerelease: false